# Generated by Django 4.1.6 on 2023-02-07 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_alter_team_fifa_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="titles",
            new_name="tittles",
        ),
    ]
