# Generated by Django 4.1.6 on 2023-02-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0004_rename_tittles_team_titles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="fifa_code",
            field=models.CharField(max_length=3),
        ),
    ]
